version: "3.7"
services:
  app:
    build:
      args:
        user: cehatrol
        uid: 1000
      context: ./
      dockerfile: docker/app/Dockerfile
    image: cehatrol
    container_name: cehatrol-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cehatrol

  db:
    image: mysql:5.7
    container_name: cehatrol-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - cehatrol

  nginx:
    image: nginx:alpine
    container_name: cehatrol-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - cehatrol


networks:
  cehatrol:
    driver: bridge
